spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/amigoscode
    username: amigoscode
    password: password
  flyway:
    enabled: true
    schemas: public

server:
  error:
    include-binding-errors: always
    include-message: always


